/*
 * 异步获取歌词
 */
const SET_SINGER = 'SET_SINGER';
const REQUEST_SINGER_LYRIC = 'REQUEST_SINGER_LYRIC';
const RECEIVE_SINGER_LYRIC = 'RECEIVE_SINGER_LYRIC';
const FAIL_SINGER_LYRIC = 'FAIL_SINGER_LYRIC';
const CLEAR_SINGER = 'CLEAR_SINGER';

export {
	SET_SINGER,
	CLEAR_SINGER,
	REQUEST_SINGER_LYRIC,
	RECEIVE_SINGER_LYRIC,
	FAIL_SINGER_LYRIC
}
