/*
 * 歌曲播放
 */

const SET_PLAYING_STATE = 'SET_PLAYING_STATE';
const SET_FULL_SCREEN = 'SET_FULL_SCREEN';
const SET_PLAYLIST = 'SET_PLAYLIST';
const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST';
const SET_PALY_MODE = 'SET_PALY_MODE';
const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';
const SET_CURRENT_MID = 'SET_CURRENT_MID';
const SET_LYRIC_FLAG = 'SET_LYRIC_FLAG';
const SET_SONG_LIKE = 'SET_SONG_LIKE';



export {
	SET_PLAYING_STATE, 
	SET_FULL_SCREEN,
	SET_PLAYLIST,
	SET_SEQUENCE_LIST,
	SET_PALY_MODE,
	SET_CURRENT_INDEX,
	SET_CURRENT_MID,
	SET_LYRIC_FLAG,
	SET_SONG_LIKE
	}
