//getSingerDetail
export const REQUEST_SINGER_DETAIL = 'REQUEST_SINGER_DETAIL';
export const RECEIVE_SINGER_DETAIL = 'RECEIVE_SINGER_DETAIL';
export const FAIL_SINGER_DETAIL = 'FAIL_SINGER_DETAIL';
export const INVALIDATE_SINGER_DETAIL = 'INVALIDATE_SINGER_DETAIL';
export const UPDATE_SINGET_DETAIL = 'UPDATE_SINGET_DETAIL';
