/*
 * 搜索key
 */

export const REQUEST_SEARCH_KEY = 'REQUEST_SEARCH_KEY';
export const RECEIVE_SEARCH_KEY = 'RECEIVE_SEARCH_KEY';
export const FAIL_SEARCH_KEY = 'FAIL_SEARCH_KEY';
export const INVALIDATE_SEARCH_KEY = 'INVALIDATE_SEARCH_KEY';

export const SELECT_SEARCH_KEY = 'SELECT_SEARCH_KEY'; 
export const SET_SUBBRIT_PAGE = 'SET_SUBBRIT_PAGE';
export const SET_SUBBRIT_HASMORE = 'SET_SUBBRIT_HASMORE';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY'; 


/*
 * 搜索历史
 */

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY';
export const GET_SEARCH_HISTORY = 'GET_SEARCH_HISTORY';
export const DELETE_SEARCH_HISTORY = 'DELETE_SEARCH_HISTORY';
export const CLEAR_SEARCH_HISTORY = 'CLEAR_SEARCH_HISTORY';
